name: Build

on:
    push:
        branches: [ "master", "unit_testing" ]
    pull_request:

jobs:
    build_ubuntu:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: make
          run: make
        - name: unit-tests
          run: make t
    build_macos:
        runs-on: macos-12
        steps:
        - uses: actions/checkout@v3
        - name: make
          run: make
